version: "3"
services:
  api:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: balance-api
  client:
    build: ./client
    ports:
      -  "80:80"
    container_name: balance-client
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: balance-db